# Ids of menu
MAIN_MENU_ID = 0
REGISTRATION_MENU_ID = 1

# Ids of the registration menu items
REGISTRATION_ITEM_FIRST_NAME = 0
REGISTRATION_ITEM_LAST_NAME = 1
REGISTRATION_ITEM_AGE = 2

MAIN_MENU_PREFIX = "main_menu_"
